spring:
  datasource: # 数据库配置
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #org.gjt.mm.mysql.Driver
    url: jdbc:mysql://39.103.152.104:3306/t_order_local?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  redis:
    host: 192.168.1.100
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-active: 8
        max-wait: 30000 #30000-1
        max-idle: 8
        min-idle: 0
    cache:
      redis:
        time-to-live: -1

#eureka:
#  client:
#    register-with-eureka: true  #表示是否将自己注册进 eurekaserver 默认true
#    fetch-registry: true   # 是否从eurekaserver 抓取已有的注册信息，默认为true  单节点无所谓，集群必须设置true 才能配合Ribbon 使用负载均衡
#    service-url:
#      defaultZone: http://121.89.213.171:7001/eureka/
#      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#  instance:
#    instance-id: email80
#    prefer-ip-address: true
#    # Eureka客户端向服务心跳的时间间隔是1s，默认是30秒
#    lease-renewal-interval-in-seconds: 1
#    # Eureka服务端在收到一次心跳后等待时间上限是2s，默认是90s，超时将剔除该微服务，其实Eureka服务端已经设置了，可能就是也告诉服务提供者一下
#    lease-expiration-duration-in-seconds: 2
fdfs:
  so-timeout: 3000
  connect-timeout: 1000
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 220.194.188.25:22122

upload:  #文件上传方式   false  上传到本地    ture  上传到文件服务器
  file:
    way: false