spring:
  datasource: # 数据库配置
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root